import type { Product, Category } from '../types.ts';

export const categories: Category[] = [
  {
    id: 'electronics',
    name: 'Electronics',
    description: 'Electronic devices and gadgets',
    subcategories: [
      {
        id: 'smartphones',
        name: 'Smartphones',
        description: 'Mobile phones and accessories',
        parentId: 'electronics',
        subcategories: [],
        productCount: 15,
      },
      {
        id: 'laptops',
        name: 'Laptops',
        description: 'Portable computers',
        parentId: 'electronics',
        subcategories: [],
        productCount: 8,
      },
    ],
    productCount: 23,
  },
  {
    id: 'clothing',
    name: 'Clothing',
    description: 'Fashion and apparel',
    subcategories: [
      {
        id: 'mens-clothing',
        name: 'Men\'s Clothing',
        description: 'Clothing for men',
        parentId: 'clothing',
        subcategories: [],
        productCount: 25,
      },
      {
        id: 'womens-clothing',
        name: 'Women\'s Clothing',
        description: 'Clothing for women',
        parentId: 'clothing',
        subcategories: [],
        productCount: 30,
      },
    ],
    productCount: 55,
  },
];

export const products: Product[] = [
  {
    id: 'iphone-15-pro',
    name: 'iPhone 15 Pro',
    description: 'Latest Apple smartphone with A17 Pro chip and titanium design',
    price: 999,
    currency: 'USD',
    category: 'electronics',
    subcategory: 'smartphones',
    brand: 'Apple',
    sku: 'IPHONE15PRO256',
    inStock: true,
    stockQuantity: 50,
    images: [
      'https://example.com/iphone15pro-1.jpg',
      'https://example.com/iphone15pro-2.jpg',
    ],
    attributes: {
      storage: '256GB',
      color: 'Natural Titanium',
      display: '6.1-inch Super Retina XDR',
      camera: '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
    },
    rating: 4.8,
    reviewCount: 1247,
    tags: ['smartphone', 'apple', 'premium', 'new'],
    createdAt: '2024-09-22T10:00:00Z',
    updatedAt: '2024-12-15T14:30:00Z',
  },
  {
    id: 'macbook-pro-m3',
    name: 'MacBook Pro 14-inch M3',
    description: 'Powerful laptop with M3 chip for professional workflows',
    price: 1599,
    currency: 'USD',
    category: 'electronics',
    subcategory: 'laptops',
    brand: 'Apple',
    sku: 'MBP14M3512',
    inStock: true,
    stockQuantity: 25,
    images: [
      'https://example.com/macbook-pro-m3-1.jpg',
      'https://example.com/macbook-pro-m3-2.jpg',
    ],
    attributes: {
      processor: 'Apple M3',
      memory: '8GB',
      storage: '512GB SSD',
      display: '14.2-inch Liquid Retina XDR',
      battery: 'Up to 22 hours',
    },
    rating: 4.9,
    reviewCount: 892,
    tags: ['laptop', 'apple', 'professional', 'm3'],
    createdAt: '2023-10-30T10:00:00Z',
    updatedAt: '2024-12-10T09:15:00Z',
  },
  {
    id: 'mens-casual-shirt',
    name: 'Men\'s Casual Cotton Shirt',
    description: 'Comfortable cotton shirt perfect for everyday wear',
    price: 49.99,
    currency: 'USD',
    category: 'clothing',
    subcategory: 'mens-clothing',
    brand: 'StyleCo',
    sku: 'MCCS001BLM',
    inStock: true,
    stockQuantity: 100,
    images: [
      'https://example.com/mens-shirt-blue-1.jpg',
      'https://example.com/mens-shirt-blue-2.jpg',
    ],
    attributes: {
      material: '100% Cotton',
      size: 'Medium',
      color: 'Blue',
      fit: 'Regular',
      care: 'Machine washable',
    },
    rating: 4.3,
    reviewCount: 156,
    tags: ['shirt', 'casual', 'cotton', 'mens'],
    createdAt: '2024-03-15T08:00:00Z',
    updatedAt: '2024-12-01T16:45:00Z',
  },
  {
    id: 'womens-dress',
    name: 'Women\'s Summer Dress',
    description: 'Elegant summer dress with floral pattern',
    price: 79.99,
    currency: 'USD',
    category: 'clothing',
    subcategory: 'womens-clothing',
    brand: 'FashionForward',
    sku: 'WSD001FLR',
    inStock: false,
    stockQuantity: 0,
    images: [
      'https://example.com/womens-dress-floral-1.jpg',
      'https://example.com/womens-dress-floral-2.jpg',
    ],
    attributes: {
      material: 'Polyester blend',
      size: 'Medium',
      color: 'Floral print',
      length: 'Midi',
      neckline: 'V-neck',
    },
    rating: 4.6,
    reviewCount: 203,
    tags: ['dress', 'summer', 'floral', 'womens'],
    createdAt: '2024-04-20T12:00:00Z',
    updatedAt: '2024-12-14T11:20:00Z',
  },
];
