import type { Product, Category } from '../../types.js';

export const categories: Category[] = [
    {
        id: 'electronics',
        name: 'Electronics',
        description: 'Electronic devices and gadgets',
        subcategories: [
            {
                id: 'smartphones',
                name: 'Smartphones',
                description: 'Mobile phones and accessories',
                parentId: 'electronics',
                subcategories: [],
                productCount: 100,
            },
            {
                id: 'laptops',
                name: 'Laptops',
                description: 'Portable computers',
                parentId: 'electronics',
                subcategories: [],
                productCount: 100,
            },
            {
                id: 'tablets',
                name: 'Tablets',
                description: 'Tablet devices',
                parentId: 'electronics',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'audio',
                name: 'Audio',
                description: 'Headphones, speakers, and audio devices',
                parentId: 'electronics',
                subcategories: [],
                productCount: 50,
            },
        ],
        productCount: 300,
    },
    {
        id: 'clothing',
        name: 'Clothing',
        description: 'Fashion and apparel',
        subcategories: [
            {
                id: 'mens-clothing',
                name: "Men's Clothing",
                description: 'Clothing for men',
                parentId: 'clothing',
                subcategories: [],
                productCount: 100,
            },
            {
                id: 'womens-clothing',
                name: "Women's Clothing",
                description: 'Clothing for women',
                parentId: 'clothing',
                subcategories: [],
                productCount: 100,
            },
            {
                id: 'kids-clothing',
                name: "Kids' Clothing",
                description: 'Clothing for kids',
                parentId: 'clothing',
                subcategories: [],
                productCount: 50,
            },
        ],
        productCount: 250,
    },
    {
        id: 'home',
        name: 'Home & Kitchen',
        description: 'Home appliances and kitchenware',
        subcategories: [
            {
                id: 'appliances',
                name: 'Appliances',
                description: 'Home appliances',
                parentId: 'home',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'cookware',
                name: 'Cookware',
                description: 'Cooking utensils and cookware',
                parentId: 'home',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'decor',
                name: 'Home Decor',
                description: 'Decorative items',
                parentId: 'home',
                subcategories: [],
                productCount: 50,
            },
        ],
        productCount: 150,
    },
    {
        id: 'sports',
        name: 'Sports & Outdoors',
        description: 'Sports equipment and outdoor gear',
        subcategories: [
            {
                id: 'fitness',
                name: 'Fitness',
                description: 'Fitness equipment',
                parentId: 'sports',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'camping',
                name: 'Camping',
                description: 'Camping gear',
                parentId: 'sports',
                subcategories: [],
                productCount: 25,
            },
            {
                id: 'cycling',
                name: 'Cycling',
                description: 'Bikes and accessories',
                parentId: 'sports',
                subcategories: [],
                productCount: 25,
            },
        ],
        productCount: 100,
    },
    {
        id: 'beauty',
        name: 'Beauty & Personal Care',
        description: 'Cosmetics and personal care products',
        subcategories: [
            {
                id: 'skincare',
                name: 'Skincare',
                description: 'Skincare products',
                parentId: 'beauty',
                subcategories: [],
                productCount: 30,
            },
            {
                id: 'haircare',
                name: 'Haircare',
                description: 'Haircare products',
                parentId: 'beauty',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'makeup',
                name: 'Makeup',
                description: 'Makeup products',
                parentId: 'beauty',
                subcategories: [],
                productCount: 20,
            },
        ],
        productCount: 70,
    },
    {
        id: 'toys',
        name: 'Toys & Games',
        description: 'Toys, games, and puzzles',
        subcategories: [
            {
                id: 'action-figures',
                name: 'Action Figures',
                description: 'Action figures and collectibles',
                parentId: 'toys',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'puzzles',
                name: 'Puzzles',
                description: 'Puzzles and brain teasers',
                parentId: 'toys',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'board-games',
                name: 'Board Games',
                description: 'Board games for all ages',
                parentId: 'toys',
                subcategories: [],
                productCount: 20,
            },
        ],
        productCount: 60,
    },
    {
        id: 'books',
        name: 'Books',
        description: 'Books and literature',
        subcategories: [
            {
                id: 'fiction',
                name: 'Fiction',
                description: 'Fiction books',
                parentId: 'books',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'non-fiction',
                name: 'Non-Fiction',
                description: 'Non-fiction books',
                parentId: 'books',
                subcategories: [],
                productCount: 50,
            },
            {
                id: 'children',
                name: 'Children',
                description: 'Children books',
                parentId: 'books',
                subcategories: [],
                productCount: 20,
            },
        ],
        productCount: 120,
    },
    {
        id: 'automotive',
        name: 'Automotive',
        description: 'Car accessories and parts',
        subcategories: [
            {
                id: 'car-electronics',
                name: 'Car Electronics',
                description: 'Electronics for cars',
                parentId: 'automotive',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'interior',
                name: 'Interior Accessories',
                description: 'Interior car accessories',
                parentId: 'automotive',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'exterior',
                name: 'Exterior Accessories',
                description: 'Exterior car accessories',
                parentId: 'automotive',
                subcategories: [],
                productCount: 20,
            },
        ],
        productCount: 60,
    },
    {
        id: 'grocery',
        name: 'Grocery',
        description: 'Food and beverages',
        subcategories: [
            {
                id: 'snacks',
                name: 'Snacks',
                description: 'Snacks and treats',
                parentId: 'grocery',
                subcategories: [],
                productCount: 30,
            },
            {
                id: 'beverages',
                name: 'Beverages',
                description: 'Drinks and beverages',
                parentId: 'grocery',
                subcategories: [],
                productCount: 30,
            },
            {
                id: 'pantry',
                name: 'Pantry',
                description: 'Pantry staples',
                parentId: 'grocery',
                subcategories: [],
                productCount: 40,
            },
        ],
        productCount: 100,
    },
    {
        id: 'office',
        name: 'Office Supplies',
        description: 'Office and school supplies',
        subcategories: [
            {
                id: 'stationery',
                name: 'Stationery',
                description: 'Pens, paper, and stationery',
                parentId: 'office',
                subcategories: [],
                productCount: 30,
            },
            {
                id: 'furniture',
                name: 'Office Furniture',
                description: 'Desks, chairs, and furniture',
                parentId: 'office',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'organization',
                name: 'Organization',
                description: 'Organizational tools',
                parentId: 'office',
                subcategories: [],
                productCount: 20,
            },
        ],
        productCount: 70,
    },
    {
        id: 'pets',
        name: 'Pet Supplies',
        description: 'Products for pets',
        subcategories: [
            {
                id: 'dog-supplies',
                name: 'Dog Supplies',
                description: 'Products for dogs',
                parentId: 'pets',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'cat-supplies',
                name: 'Cat Supplies',
                description: 'Products for cats',
                parentId: 'pets',
                subcategories: [],
                productCount: 20,
            },
            {
                id: 'bird-supplies',
                name: 'Bird Supplies',
                description: 'Products for birds',
                parentId: 'pets',
                subcategories: [],
                productCount: 10,
            },
        ],
        productCount: 50,
    },
];

// 1000+ realistic products generated for all categories and subcategories
import { faker } from '@faker-js/faker';

function generateProducts(): Product[] {
    const categories = [
        {
            id: 'electronics',
            sub: ['smartphones', 'laptops', 'tablets', 'audio'],
        },
        {
            id: 'clothing',
            sub: ['mens-clothing', 'womens-clothing', 'kids-clothing'],
        },
        { id: 'home', sub: ['appliances', 'cookware', 'decor'] },
        { id: 'sports', sub: ['fitness', 'camping', 'cycling'] },
        { id: 'beauty', sub: ['skincare', 'haircare', 'makeup'] },
        { id: 'toys', sub: ['action-figures', 'puzzles', 'board-games'] },
        { id: 'books', sub: ['fiction', 'non-fiction', 'children'] },
        { id: 'automotive', sub: ['car-electronics', 'interior', 'exterior'] },
        { id: 'grocery', sub: ['snacks', 'beverages', 'pantry'] },
        { id: 'office', sub: ['stationery', 'furniture', 'organization'] },
        { id: 'pets', sub: ['dog-supplies', 'cat-supplies', 'bird-supplies'] },
    ];
    const brands = [
        'Apple',
        'Samsung',
        'Sony',
        'LG',
        'Nike',
        'Adidas',
        'StyleCo',
        'FashionForward',
        'KitchenPro',
        'FitGear',
        'BookWorld',
        'AutoPlus',
        'Snacky',
        'OfficeMate',
        'PetPal',
    ];
    const products: Product[] = [];
    let idCounter = 1;
    for (const cat of categories) {
        for (const sub of cat.sub) {
            for (let i = 0; i < 30; i++) {
                const brand = faker.helpers.arrayElement(brands);
                const name = faker.commerce.productName();
                const price = Number(faker.commerce.price({ min: 10, max: 2000 }));
                const inStock = faker.datatype.boolean();
                const stockQuantity = inStock ? faker.number.int({ min: 1, max: 200 }) : 0;
                const images = [faker.image.urlPicsumPhotos(), faker.image.urlPicsumPhotos()];
                const attributes = {
                    color: faker.color.human(),
                    size: faker.helpers.arrayElement(['Small', 'Medium', 'Large', 'XL', 'One Size']),
                    material: faker.commerce.productMaterial(),
                };
                const rating = Number(
                    faker.number.float({
                        min: 3.0,
                        max: 5.0,
                        fractionDigits: 1,
                    }),
                );
                const reviewCount = faker.number.int({ min: 0, max: 2000 });
                const tags = [cat.id, sub, brand.toLowerCase()];
                const createdAt = faker.date.past({ years: 2 }).toISOString();
                const updatedAt = faker.date.recent({ days: 60 }).toISOString();
                products.push({
                    id: `prod-${idCounter++}`,
                    name,
                    description: faker.commerce.productDescription(),
                    price,
                    currency: 'USD',
                    category: cat.id,
                    subcategory: sub,
                    brand,
                    sku: faker.string.alphanumeric({
                        length: 10,
                        casing: 'upper',
                    }),
                    inStock,
                    stockQuantity,
                    images,
                    attributes,
                    rating,
                    reviewCount,
                    tags,
                    createdAt,
                    updatedAt,
                });
            }
        }
    }
    // Add a few special products (originals)
    products.push(
        {
            id: 'iphone-15-pro',
            name: 'iPhone 15 Pro',
            description: 'Latest Apple smartphone with A17 Pro chip and titanium design',
            price: 999,
            currency: 'USD',
            category: 'electronics',
            subcategory: 'smartphones',
            brand: 'Apple',
            sku: 'IPHONE15PRO256',
            inStock: true,
            stockQuantity: 50,
            images: ['https://example.com/iphone15pro-1.jpg', 'https://example.com/iphone15pro-2.jpg'],
            attributes: {
                storage: '256GB',
                color: 'Natural Titanium',
                display: '6.1-inch Super Retina XDR',
                camera: '48MP Main + 12MP Ultra Wide + 12MP Telephoto',
            },
            rating: 4.8,
            reviewCount: 1247,
            tags: ['smartphone', 'apple', 'premium', 'new'],
            createdAt: '2024-09-22T10:00:00Z',
            updatedAt: '2024-12-15T14:30:00Z',
        },
        {
            id: 'macbook-pro-m3',
            name: 'MacBook Pro 14-inch M3',
            description: 'Powerful laptop with M3 chip for professional workflows',
            price: 1599,
            currency: 'USD',
            category: 'electronics',
            subcategory: 'laptops',
            brand: 'Apple',
            sku: 'MBP14M3512',
            inStock: true,
            stockQuantity: 25,
            images: ['https://example.com/macbook-pro-m3-1.jpg', 'https://example.com/macbook-pro-m3-2.jpg'],
            attributes: {
                processor: 'Apple M3',
                memory: '8GB',
                storage: '512GB SSD',
                display: '14.2-inch Liquid Retina XDR',
                battery: 'Up to 22 hours',
            },
            rating: 4.9,
            reviewCount: 892,
            tags: ['laptop', 'apple', 'professional', 'm3'],
            createdAt: '2023-10-30T10:00:00Z',
            updatedAt: '2024-12-10T09:15:00Z',
        },
        {
            id: 'mens-casual-shirt',
            name: "Men's Casual Cotton Shirt",
            description: 'Comfortable cotton shirt perfect for everyday wear',
            price: 49.99,
            currency: 'USD',
            category: 'clothing',
            subcategory: 'mens-clothing',
            brand: 'StyleCo',
            sku: 'MCCS001BLM',
            inStock: true,
            stockQuantity: 100,
            images: ['https://example.com/mens-shirt-blue-1.jpg', 'https://example.com/mens-shirt-blue-2.jpg'],
            attributes: {
                material: '100% Cotton',
                size: 'Medium',
                color: 'Blue',
                fit: 'Regular',
                care: 'Machine washable',
            },
            rating: 4.3,
            reviewCount: 156,
            tags: ['shirt', 'casual', 'cotton', 'mens'],
            createdAt: '2024-03-15T08:00:00Z',
            updatedAt: '2024-12-01T16:45:00Z',
        },
        {
            id: 'womens-dress',
            name: "Women's Summer Dress",
            description: 'Elegant summer dress with floral pattern',
            price: 79.99,
            currency: 'USD',
            category: 'clothing',
            subcategory: 'womens-clothing',
            brand: 'FashionForward',
            sku: 'WSD001FLR',
            inStock: false,
            stockQuantity: 0,
            images: ['https://example.com/womens-dress-floral-1.jpg', 'https://example.com/womens-dress-floral-2.jpg'],
            attributes: {
                material: 'Polyester blend',
                size: 'Medium',
                color: 'Floral print',
                length: 'Midi',
                neckline: 'V-neck',
            },
            rating: 4.6,
            reviewCount: 203,
            tags: ['dress', 'summer', 'floral', 'womens'],
            createdAt: '2024-04-20T12:00:00Z',
            updatedAt: '2024-12-14T11:20:00Z',
        },
    );
    return products;
}

export const products: Product[] = generateProducts();
